# Generated by Django 5.2.1 on 2025-06-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
