# Generated by Django 5.2.1 on 2025-06-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_parkingspot_spot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.IntegerField(max_length=100, unique=True),
        ),
    ]
